name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build my project <img draggable="false" role="img" class="emoji" alt="✨" src="https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/twemoji/2/svg/2728.svg" scale="0">
    runs-on: ubuntu-latest
    steps:
     
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
     
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
 
      # Test
      - name: Run tests
        uses: webbertakken/unity-test-runner@v1.3
        with:
          unityVersion: 2019.3.9f1
 
      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v0.10
        with:
          unityVersion: 2019.3.9f1
          targetPlatform: StandaloneWindows64
 
      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
